### ISSUE TITLE
Library Prep functionality

### ISSUE THREAD

**Issue by moonjo-geno** [BU-ISCIII/iSkyLIMS#18] opened 2021-07-20 09:25 UTC
Hello iSkyLIMS developers and users,

We were wondering if there is a functionality for library prep. We noticed that the README talks about how iSkyLIMS guides through the process from library prep to data delivery to the dry lab. I read the wiki but didn't see much about the library prep stage other than adding the name of the library kit. Is there some functionality where we can enter data library prep related data such as qubits, tapestation, etc.? (We are hoping to record information such as DNA prep and Exome capture as well.)

Thank you in advance,
Moonjo

**Comment by icuesta** [comment] 2021-07-20 09:37
Thanks for your interest @moonjo-geno. This will be included in the new iskylims version which will be released we hope, very soon

**Comment by luissian** [comment] 2021-07-20 11:59
Hello Moonjo.
As icuesta mentions we hope to release a new iSkyLIMS version soon. 
The information that you are requesting for , I believe it is included in the new coming release. 
I would like to recommend you to go to https://iskylims.readthedocs.io/en/latest/ for reading the documentation of this new release. 
We are creating a Docker file for helping beginner users  to evaluate iSkyLIMS. You can install by following the instructions described in :
https://iskylims.readthedocs.io/en/latest/Installation.html
Please keep in mind that code is not stable and we are adding/correcting lines of code for the functionality that is not completed yet. 
Any bug that you find or changes in documentation for get it more readable is really, really very welcome.
Thanks for your interest.
Luis

**Comment by moonjo-geno** [comment] 2021-07-21 01:28
Hello Luis,
Thank you for the quick reply. I followed the instruction to check out the functionality and this is the error that I'm getting:
```
% sh iskylims_install.sh
--2021-07-21 10:25:53--  https://raw.githubusercontent.com/BU-ISCIII/iSkyLIMS/develop/Dockerfile
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1997 (2.0K) [text/plain]
Saving to: ‘Dockerfile’

Dockerfile                             100%[=========================================================================>]   1.95K  --.-KB/s    in 0s      

2021-07-21 10:25:54 (6.75 MB/s) - ‘Dockerfile’ saved [1997/1997]

--2021-07-21 10:25:54--  https://raw.githubusercontent.com/BU-ISCIII/iSkyLIMS/develop/docker-compose.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1135 (1.1K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml                     100%[=========================================================================>]   1.11K  --.-KB/s    in 0s      

2021-07-21 10:25:54 (30.9 MB/s) - ‘docker-compose.yml’ saved [1135/1135]

[+] Building 4.0s (29/31)                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                0.0s
 => => transferring dockerfile: 2.04kB                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                     3.7s
 => [internal] load build context                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                     0.0s
 => CANCELED [ 1/27] FROM docker.io/library/ubuntu:20.04@sha256:b3e2e47d016c08b3396b5ebe06ab0b711c34e7f37b98c9d37abe794b71cea0a2                    0.0s
 => => resolve docker.io/library/ubuntu:20.04@sha256:b3e2e47d016c08b3396b5ebe06ab0b711c34e7f37b98c9d37abe794b71cea0a2                               0.0s
 => => sha256:b3e2e47d016c08b3396b5ebe06ab0b711c34e7f37b98c9d37abe794b71cea0a2 1.20kB / 1.20kB                                                      0.0s
 => => sha256:778fdd9f62a6d7c0e53a97489ab3db17738bc5c1acf09a18738a2a674025eae6 529B / 529B                                                          0.0s
 => => sha256:c29284518f497b8c5f49933e74e43ca5221e69c8251e780427f7d12f716625ff 1.46kB / 1.46kB                                                      0.0s
 => CACHED [ 2/27] RUN ln -snf /usr/share/zoneinfo/Europe/Madrid /etc/localtime && echo Europe/Madrid > /etc/timezone                               0.0s
 => CACHED [ 3/27] RUN apt-get update && apt-get upgrade -y                                                                                         0.0s
 => CACHED [ 4/27] RUN apt-get install -y     lightdm git apt-utils libcairo2 libcairo2-dev  wget gnuplot python3-pip     libmysqlclient-dev apach  0.0s
 => CACHED [ 5/27] RUN wget https://github.com/Illumina/interop/releases/download/v1.1.15/InterOp-1.1.15-Linux-GNU.tar.gz                           0.0s
 => CACHED [ 6/27] RUN tar -xvf  InterOp-1.1.15-Linux-GNU.tar.gz                                                                                    0.0s
 => CACHED [ 7/27] RUN ln -s InterOp-1.1.15-Linux-GNU interop                                                                                       0.0s
 => CACHED [ 8/27] RUN rm InterOp-1.1.15-Linux-GNU.tar.gz                                                                                           0.0s
 => CACHED [ 9/27] RUN mkdir /opt/iSkyLIMS                                                                                                          0.0s
 => CACHED [10/27] WORKDIR /opt/iSkyLIMS                                                                                                            0.0s
 => CACHED [11/27] RUN git clone https://github.com/BU-ISCIII/iSkyLIMS.git .                                                                        0.0s
 => CACHED [12/27] RUN git submodule init                                                                                                           0.0s
 => CACHED [13/27] RUN git checkout develop                                                                                                         0.0s
 => CACHED [14/27] RUN git submodule init                                                                                                           0.0s
 => CACHED [15/27] RUN git submodule update --recursive --checkout                                                                                  0.0s
 => CACHED [16/27] RUN cd iSkyLIMS_wetlab git                                                                                                       0.0s
 => CACHED [17/27] RUN mkdir -p /opt/iSkyLIMS/documents/wetlab/tmp                                                                                  0.0s
 => CACHED [18/27] RUN mkdir -p /opt/iSkyLIMS/documents/drylab                                                                                      0.0s
 => CACHED [19/27] RUN mkdir -p /opt/iSkyLIMS/logs                                                                                                  0.0s
 => CACHED [20/27] RUN python3 -m pip install -r conf/pythonPackagesRequired.txt                                                                    0.0s
 => CACHED [21/27] RUN django-admin startproject iSkyLIMS .                                                                                         0.0s
 => CACHED [22/27] RUN /bin/bash -c 'grep ^SECRET iSkyLIMS/settings.py > ~/.secret'                                                                 0.0s
 => CACHED [23/27] RUN cp conf/settings.py /opt/iSkyLIMS/iSkyLIMS/.                                                                                 0.0s
 => CACHED [24/27] RUN cp conf/urls.py /opt/iSkyLIMS/iSkyLIMS/                                                                                      0.0s
 => ERROR [25/27] COPY scripts/migrations /opt/iSkyLIMS/                                                                                            0.0s
------
 > [25/27] COPY scripts/migrations /opt/iSkyLIMS/:
------
failed to compute cache key: "/scripts/migrations" not found: not found
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web1.depends_on contains an invalid type, it should be an array, or an object
Waiting 30 seconds for starting dabase and web services...
Creating the database structure for iSkyLIMS
Error: No such container: iskylims_installation_web1_1
Error: No such container: iskylims_installation_web1_1
Error: No such container: iskylims_installation_web1_1
Loading in database initial data
Error: No such container: iskylims_installation_web1_1
Creating super user 
Error: No such container: iskylims_installation_web1_1
chown: moonjo: illegal group name
```

**Comment by luissian** [comment] 2021-07-21 11:36
Hello Moonjo
Really sorry, I did not move the files from my testing directory to iSkyLIMS repository . 
Could you please delete the container and create it again from scratch??
Thanks Luis

**Comment by moonjo-geno** [comment] 2021-07-22 01:51
Yup. I've tried and this is the error I'm getting:
 ```
=> => naming to docker.io/library/isky_new_lims_web1                                                                                               0.0s
Successfully built 3aefc74d791402d33d9ac529e1bc743dd34452a29de6f9143b335f05d57bd739
WARNING: Image for service web1 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating db1 ... done
Creating isky_new_lims_web1_1 ... done
Waiting 30 seconds for starting dabase and web services...
Creating the database structure for iSkyLIMS
Error: No such container: iskylims_installation_web1_1
Error: No such container: iskylims_installation_web1_1
Error: No such container: iskylims_installation_web1_1
Loading in database initial data
Error: No such container: iskylims_installation_web1_1
Creating super user 
Error: No such container: iskylims_installation_web1_1
chown: moonjo: illegal group name
```
I think the script refers to iskylims_installation_web1_1 and it should be isky_new_lims_web1_1

But them I'm getting this error:

`    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: Problem installing fixture '/opt/iSkyLIMS/conf/new_installation_loading_tables.json': Could not load iSkyLIMS_core.MoleculeType(pk=1): (1146, "Table 'iSkyLIMS.iSkyLIMS_core_moleculetype' doesn't exist")`

**Comment by luissian** [comment] 2021-07-22 06:50
Hello Moonjo.
Sorry for the issues you get.
The container name that you get is isky_new_lims_web1_1 and not iskylims_installation_web1_1
Could you start up the docker container with :
    docker-compose up -d 

and then manually execute one by one the commands, that you get error by  changing the docker container name that was in file for the one that you get it. Like this:

docker exec -it isky_new_lims_web1_1 python3 manage.py migrate
docker exec -it isky_new_lims_web1_1 python3 manage.py makemigrations django_utils iSkyLIMS_core iSkyLIMS_wetlab iSkyLIMS_drylab iSkyLIMS_clinic
docker exec -it isky_new_lims_web1_1 python3 manage.py migrate

echo "Loading in database initial data"
docker exec -it isky_new_lims_web1_1 python3 manage.py loaddata conf/new_installation_loading_tables.json

echo "Creating super user "
docker exec -it isky_new_lims_web1_1 python3 manage.py createsuperuser

I do not know why is changing the container name, if you know the reason , please share it with me.
Sorry again for these issues.

**Comment by luissian** [comment] 2021-07-22 21:44
Hello Moonjo.
I run the docker script on a different computer and I get a different container name.
I have asked to a friend of mine to execute the script and get a complete different name.
As mention you before you need to change the docker name in the script for the one that is in your installation.

I will improve the script to fetch the container name that docker is given, but in the meantime could you please run manually the commands I told you before by changing the docker container name by thse one you get in the installation?
BR
Lui

**Comment by moonjo-geno** [comment] 2021-07-23 00:46
They all ran without error. I had to add the following
`docker exec -it isky_new_lims_web1_1 python3 manage.py runserver 0:8000` 
However, when clicked around, I'd get the following errors:
`[23/Jul/2021 02:41:02] "GET / HTTP/1.1" 200 12757
[23/Jul/2021 02:41:07] "GET /clinic/ HTTP/1.1" 200 13207
[23/Jul/2021 02:41:07] "GET /static/iSkyLIMS_common_static/css/customized.css HTTP/1.1" 200 12741
[23/Jul/2021 02:41:07] "GET /static/iSkyLIMS_clinic/img/logo_iSkyLIMS_clinic.png HTTP/1.1" 200 1412
[23/Jul/2021 02:41:07] "GET /static/iSkyLIMS_common_static/img/clinic_ambulance_reduce.jpg HTTP/1.1" 200 74944
[23/Jul/2021 02:41:07] "GET /static/iSkyLIMS.ico HTTP/1.1" 200 1150
[23/Jul/2021 02:41:21] "GET /clinic/createSampleProjects HTTP/1.1" 200 14425
[23/Jul/2021 02:42:07] "POST /clinic/createSampleProjects HTTP/1.1" 200 15231
[23/Jul/2021 02:42:11] "GET /clinic/defineSampleProjectFields=1 HTTP/1.1" 200 16042
[23/Jul/2021 02:42:11] "GET /static/iSkyLIMS_common_static/js/jquery/v3.4.1/jquery-3.4.1.min.js HTTP/1.1" 200 88145
[23/Jul/2021 02:42:11] "GET /static/iSkyLIMS_common_static/js/jsuites/v2/jsuites.js HTTP/1.1" 200 114305
[23/Jul/2021 02:42:11] "GET /static/iSkyLIMS_common_static/css/jexcel/v3/jexcel.css HTTP/1.1" 200 17897
[23/Jul/2021 02:42:11] "GET /static/iSkyLIMS_common_static/css/jsuites/v2/jsuites.css HTTP/1.1" 200 48551
[23/Jul/2021 02:42:11] "GET /static/iSkyLIMS_common_static/js/jexcel/v3/jexcel.js HTTP/1.1" 200 428328
Internal Server Error: /clinic/defineSampleProjectFields=1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''`

and 

`...
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 837, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'sampleProjectFieldOrder' expected a number but got ''.
`

`Internal Server Error: /clinic/addCommercialKit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/iSkyLIMS/iSkyLIMS_clinic/views.py", line 31, in add_commercial_kit
    commercial_kits_data = get_data_for_commercial_kits()
TypeError: get_data_for_commercial_kits() missing 1 required positional argument: 'platform'
`

**Comment by luissian** [comment] 2021-07-23 17:23
Hello Moonjo.
I am happy that you get it up.
I knew that you will find errors, remember that are still working on the code. The errors that you get is because there is no information in some tables.
Bur thanks a lot for the errors you found so we can focus on solving.
Because you were interesting in record information to the samples,  I would like if you could do the following actions:
In navigator type localhost:8000/admin
This will open the django administration page
You will see, on the top  left side, "groups". click on "+ add " links and define 2 groups:
WetlabManager
ServiceManager

After saving the last one you will return to the main page and then this time click on the "Users" . Then on the right side, click on de "admin" user.
In the new window, scroll down until you get the "Groups" boxes inside the Permission section.
Move both (WetlabManager and ServiceManager) from available groups to chosen ones and save it.

Then go the main page on iSkyLIMS (localhost:8000) and click on the Massive Sequencing picture.
You can see now that there are new options on the main menu.
Now is time to configure iSkyLIMS with all parameters that you need to record . 
Go to documentation page to follow all steps or configuration
https://iskylims.readthedocs.io/en/latest/massiveSequencing/wetlabManagerConfiguration.html

 I hope that you could fit all data that you need. Let me know if you have some problems with then.
 If you get some errors , please give the steps you did to try to reproduce the error from mi side.

**Comment by moonjo-geno** [comment] 2021-07-27 04:12
Thank you for your information and help. 

Would it be possible to have the installation not on docker? If there's instruction, i'll follow them. I was hoping to host this on AWS so that people in the lab could use it.

**Comment by luissian** [comment] 2021-07-27 10:17
We have in mind to have a script installation for Centos7 and Ubuntu 20.04 (which are the available environments that we have), and we will prepare the instruction documentation. 
In the installation script  we will not create the database server, It is assume that server is already up . 

It will take a time to deliver this script, because we are on vacation period, but most probably it will be ready by the first week of September.

**Comment by luissian** [comment] 2021-08-21 09:04
Close the issue.

**Closed by luissian** 2021-08-21 09:04 UTC
